# Generated by Django 5.2.1 on 2025-06-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in months'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
