# Generated by Django 5.2.1 on 2025-06-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_member_plan_alter_plan_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership_type',
        ),
    ]
