# Generated by Django 5.2.1 on 2025-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_member_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Experience in years'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
